---
# --- Page Setup ---
documentclass:
  fontsize: 10pt
  papersize: a4paper
  class: article 

fontspec:
  mainfont: Lato

geometry:
  margin: .5in

# --- PDF Metadata ---
hypersetup:
  pdftitle: 'Tony Stark - Resume'
  pdfauthor: 'Tony Stark'
  pdfsubject: 'Resume'
  pdfkeywords: 'Resume'

# --- Personal ---
personal:
  name: 'Tony Stark'
  address: '10880 Malibu Point, Malibu, California 90265'
  phone: '(212) 970-4133'
  email: 'tony.stark@email.com'
  website: 'https://www.example.com/'
  prettyurl: 'tony.stark.com'

# --- Target Role ---
objective: 
  description: Innovative and visionary engineer, inventor, and business leader with expertise in advanced technology and strategic management. Known for founding Stark Industries and transforming it into a global leader in defense and energy solutions. Possesses exceptional problem-solving skills and a track record of developing groundbreaking inventions. Strong leadership abilities combined with a keen business acumen..

# --- Technical Skills ---
skills:
  programming: C, BASH, Vimscript 
  platforms: Linux (Jarvis)
  tools: Git, VIM
  communication: project documention, vimWiki
  languages: English, Russian, French, German, Hindu, Urdu
  additional: Friends with Thor.
    

# Related Course Work
relatedCourseWork:
  C1:
    - Mechanics
    - Electromagnetism
    - Thermodynamics
    - Quantum Mechanics
  C2:
    - Organic Chemistry
    - Inorganic Chemistry
    - Analytical Chemistry
    - Mechanical Engineering
  C3:
    - Electrical Engineering
    - Calculus
    - Linear Algebra
    - Differential Equations

# --- Projects ---
projects:
  - name: Resume Builder Pandoc
    githubLink: https://github.com/wilbura009/resume_builder_pandoc
    presentationLink: https://revealjs.com/
    description: An example with a presentation link.
    contribution:
    - Created a LaTeX resume template using .yaml front matter and pandoc to generate PDFs.
    - The template was used to create professional-looking resumes that were easy to read and scan.
    - The template resulted in a significant reduction in the time it took to create resumes. :)

  - name: Resume Builder Pandoc
    githubLink: https://github.com/wilbura009/resume_builder_pandoc
    presentationLink:
    description: An example with no presentation link.
    contribution:
    - Created a LaTeX resume template using .yaml front matter and pandoc to generate PDFs.
    - The template was used to create professional-looking resumes that were easy to read and scan.
    - The template resulted in a significant reduction in the time it took to create resumes. :)

# --- Education ---
education:
- year: 2002
  subject: Bachelor of Science Degree in Electrical Engineering
  institute: Massachusetts Institute of Technology (MIT)
  city: Cambridge, MA, USA.

# --- Experience ---
experience:
- year: 2008 - 2023
  employer: Stark Industries
  position: Founder and CEO
  city: Malibu, California
  description: Tutored College Algebra and Algebra for Business Majors. Instructed students individually and in groups, using various teaching methods, such as lectures, discussions, and demonstrations. Adapted teaching methods and instructional materials to meet students' varying needs and interests.

- year: 2012 - 2023
  employer: Avengers Initiative
  position: Co-Founder and Key Member
  city: Classified
  description: Played a vital role in assembling and leading a team of superheroes to protect Earth from various threats. Collaborated closely with other members to strategize and execute missions. Utilized advanced technology and engineering expertise to support the team's efforts.


- year: 2002 - 2005
  employer: Stark Industries
  position: Intern
  city: Classified
  description: Gained hands-on experience in various departments, including research and development, manufacturing, and business operations. Assisted senior engineers in product development and testing. Acquired a comprehensive understanding of the company's operations and processes.

...
